#document site: https://starship.rs/ja-JP/config/

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
\n$character\
"""

right_format = """
$cmd_duration\
$time
"""

add_newline = true 

[character]
success_symbol = '[â¯](bold green)'
error_symbol = '[â¯](bold red)'
vimcmd_symbol = '[V](bold green)'

[directory]
style = "bold cyan"
truncation_length = 10
read_only = 'ğŸ”’'
read_only_style = 'red'
truncation_symbol = 'â€¦/'
format = '[ $path ]($style)[$reak_only]($read_only_style)'

#[directory.substitutions]
#"Documents" = "ó°ˆ™ "
#"Downloads" = "ï€™ "
#"Music" = "ï€ "
#"Pictures" = "ï€¾ "

[username]
style_root = 'bold red'
style_user = 'bold green'
show_always = true
format = '[$user]($style)'

[hostname]
ssh_only = false
ssh_symbol = 'ğŸŒ '
format = '[\[](bold white)[$ssh_symbol](bold blue)[$hostname](bold green)[\]](bold white) '
disabled = false

[fill]
symbol = ' '

[cmd_duration]
min_time = 1
style = 'yellow'
format = '[$duration]($style)'
show_milliseconds = true

[time]
disabled = false
time_format = '%R'
format = '| [$time](white)'

[git_branch]
symbol = 'ï˜'
format = '[ $symbol $branch ](bold purple)'

[git_status]
format = '[$all_status$ahead_behind](bold purple)'
